package service

import (
	"math/rand"
	"time"

	"github.com/Victoria-290/home-work-otus/Progect/internal/model/auth"
	"github.com/Victoria-290/home-work-otus/Progect/internal/model/task"
	"github.com/Victoria-290/home-work-otus/Progect/internal/model/user"
	"github.com/Victoria-290/home-work-otus/Progect/internal/repository"
)

var emailCounter = 1
var taskCounter = 1

// GenerateAndStoreEntities создает и сохраняет сущности
func GenerateAndStoreEntities() {
	rand.Seed(time.Now().UnixNano())

	// Создаем пользователя
	u := user.NewUser(
		email:    "user" + string(rune(emailCounter)) + "@test.com",
		rawPassword: "pass123",
	)
	u.ID = int64(emailCounter)
	emailCounter++

	// Создаем задачу
	t := task.NewTask(
		title:       "Task #" + string(rune(taskCounter)),
		description: "Generated by scheduler",
		ownerID:     u.ID,
	)
	t.ID = int64(taskCounter)
	taskCounter++

	// Создаем токен
	token := &auth.Token{
		UserID:    u.ID,
		Token:     "some-jwt-token",
		ExpiresAt: time.Now().Add(time.Hour),
		IsRefresh: false,
	}

	// Передаем в репозиторий
	repository.Store(u)
	repository.Store(t)
	repository.Store(token)
}
