package service

import (
	"math/rand"
	"time"

	"github.com/Victoria-290/home-work-otus/Progect/internal/model/auth"
	"github.com/Victoria-290/home-work-otus/Progect/internal/model/task"
	"github.com/Victoria-290/home-work-otus/Progect/internal/model/user"
	"github.com/Victoria-290/home-work-otus/Progect/internal/repository"
)

var emailCounter = 1
var taskCounter = 1

// GenerateAndSendEntities создает сущности и отправляет их в канал
func GenerateAndSendEntities(ch chan<- repository.EntityEvent) {
	rand.Seed(time.Now().UnixNano())

	for {
		// Создаем пользователя
		u := user.NewUser(
			"user"+string(rune(emailCounter))+"@test.com",
			"pass123",
		)
		u.ID = int64(emailCounter)
		emailCounter++

		// Создаем задачу
		t := task.NewTask(
			"Task #"+string(rune(taskCounter)),
			"Generated by scheduler",
			u.ID,
		)
		t.ID = int64(taskCounter)
		taskCounter++

		// Создаем токен
		token := &auth.Token{
			UserID:    u.ID,
			Token:     "some-jwt-token",
			ExpiresAt: time.Now().Add(time.Hour),
			IsRefresh: false,
		}

		// Отправляем сущности в канал
		ch <- repository.EntityEvent{Entity: u}
		ch <- repository.EntityEvent{Entity: t}
		ch <- repository.EntityEvent{Entity: token}

		// Пауза перед следующей генерацией
		time.Sleep(1 * time.Second)
	}
}
